package io.jsonbox;

import java.util.HashMap;
import java.util.UUID;
import java.io.IOException;

public class JsonBoxStorage {
    private final Http http = new Http();
    private String id = null;
    private String boxId = null;
    private String collectionId = null;
    
    /**
     * Instance for a jsonbox.io box. The box id will be autogenerated.
     */
    public JsonBoxStorage() {
        this.id = UUID.randomUUID().toString().replaceAll("-", "");
        this.boxId = this.id;
    }

    /**
     * Instance for a jsonbox.io box.
     * @param  boxId A jsonbox.io box id. It has to be at least 20 characters long. Only alphanumeric, & and _ characters allowed.
     */
    public JsonBoxStorage(String boxId) {
        this.id = boxId;
        this.boxId = boxId;
    }

    /**
     * Instance for a jsonbox.io collection inside a box.
     * @param  boxId A jsonbox.io box id. It has to be at least 20 characters long. Only alphanumeric, & and _ characters allowed.
     * @param  collectionId A collection id inside a box. Only alphanumeric, & and _ characters allowed.
     */
    public JsonBoxStorage(String boxId, String collectionId) {
        this.id = boxId + "/" + collectionId;
        this.boxId = boxId;
        this.collectionId = collectionId;
    }

    /**
     * Create a record (HTTP POST)
     * @param  json a JSON string record to be created on jsonbox.io
     * @return      a JSON string response from jsonbox.io
     */
    public String create(String json) throws IOException {
        return http.request(this.id, null, "POST", new HashMap<String, String>(), json);
    }

    /**
     * Read all records (HTTP GET)
     * @return a JSON string response from jsonbox.io
     */
    public String read() throws IOException {
        return http.request(this.id, null, "GET",  new HashMap<String, String>(), null);
    }

    /**
     * Read all records (HTTP GET)
     * @param  filter query for filtering values, check format at: https://github.com/vasanthv/jsonbox#filtering
     * @return a JSON string response from jsonbox.io
     */
    public String readFiltering(String filter) throws IOException {
        return this.read(0, Integer.MAX_VALUE, filter);
    }

    /**
     * Read all records (HTTP GET)
     * @param  sort sort the result set by the specific field. Add a prefix "-" to sort in reverse order. (default: "-_createdOn")
     * @return a JSON string response from jsonbox.io
     */
    public String readSorting(String sort) throws IOException {
        return this.read(0, Integer.MAX_VALUE, null, sort);
    }

    /**
     * Read records with given filter parameters (HTTP GET)
     * @param  skip  skip certain number of records, it can be used for pagination. (default: 0)
     * @param  limit limit the results to a certain number of records, it can be used for pagination. (default: 20, max: 1000)
     * @return       a JSON string response from jsonbox.io
     */
    public String read(int skip, int limit) throws IOException {
        return this.read(skip, limit, null, null);
    }

    public String read(int skip, int limit, String filter) throws IOException {
        return this.read(skip, limit, filter, null);
    }

    /**
     * Read records with given filter parameters (HTTP GET)
     * @param  skip   skip certain number of records, it can be used for pagination. (default: 0)
     * @param  limit  limit the results to a certain number of records, it can be used for pagination. (default: 20, max: 1000)
     * @param  filter query for filtering values, check format at: https://github.com/vasanthv/jsonbox#filtering
     * @param  sort   sort the result set by the specific field. Add a prefix "-" to sort in reverse order. (default: "-_createdOn")
     * @return        a JSON string response from jsonbox.io
     */
    public String read(int skip, int limit, String filter, String sort) throws IOException {
        HashMap<String, String> parameters = new HashMap<String, String>();
        parameters.put("sort", sort);
        parameters.put("limit", Integer.toString(limit));
        parameters.put("skip", Integer.toString(skip));
        parameters.put("q", filter);

        return http.request(this.id, null, "GET", parameters, null);
    }

    /**
     * Update a record (HTTP PUT)
     * @param  recordId the record id (property "_id" generated by jsonbox.io on creation) to be updated.
     * @param  json     a JSON string record to be updated. Please note that this will not patch the record, it is a full update. A bulk update is not supported yet.
     * @return          a JSON string response from jsonbox.io
     */
    public String update(String recordId, String json) throws IOException {
        return http.request(this.id, recordId, "PUT",  new HashMap<String, String>(), json);
    }

    /**
     * Delete a single record (HTTP DELETE)
     * @param  recordId the record id (property "_id" generated by jsonbox.io on creation) to be deleted.
     * @return          a JSON string response from jsonbox.io
     */
    public String delete(String recordId) throws IOException {
        return http.request(this.id, recordId, "DELETE",  new HashMap<String, String>(), null);
    }

    /**
     * Delete multiple records (HTTP DELETE)
     * @param  filter query for filtering values, check format at: https://github.com/vasanthv/jsonbox#filtering
     * @return       a JSON string response from jsonbox.io
     */
    public String deleteFiltering(String filter) throws IOException {
        HashMap<String, String> parameters = new HashMap<String, String>();
        parameters.put("q", filter);

        return http.request(this.id, null, "DELETE", parameters, null);
    }

    /**
     * Get the instance box id.
     * @return instance box id.
     */
    public String getBoxId(){
        return this.boxId;
    }

    /**
     * Get the instance collection id inside a box.
     * @return collection id.
     */
    public String getCollectionId(){
        return this.collectionId;
    }
}
